### ISSUE TITLE
No Vanilla JS support?

### ISSUE THREAD

**Issue by pierremacedo** [jibon57/nativescript-mediafilepicker#12]
I don't understand why this plugin was written only for TS users. Type Script isn't even a programming language it's a superset of the real language JS and all of you know it. So please, stop ignoring JS in favor of this so called TS.

**Comment by jibon57** [comment]
@pierremacedo Thanks for your question. Actually I don't have enough experience on it. I have written this plugin for my own purposes & published it so that someone can get help. I am always using Angular for my projects but during writing this plugin I have followed the standard procedure of NativeScript. So, if that support Vanilla or any other platform then this plugin should support it. You can try it following the standard procedure but I ain't sure.

**Comment by gotroch** [comment]
@pierremacedo Have you sort it out?

**Comment by sayeed360** [comment]
For VanillaJS (Android)

const Mediafilepicker = require("nativescript-mediafilepicker").Mediafilepicker;

let options = {
        android: {
            mxcount: 1,
            enableImagePicker: true,
            enableVideoPicker: false,
            enableCameraSupport: false,
            pickFile: true
          }
    }
    mediafilepicker = new Mediafilepicker();
    
    mediafilepicker.on("getFiles", function (res) {
 
        let files = res.files;
  
        if (files.length > 0) {
  
            files = files.split(",");

            files.forEach(file => {
                let fileName = file.replace(/^.*[\/]/, '');

                console.log(file);
                console.log(fileName);

                // you can do anything here
  
            });
        }else{
            console.log("There was some problem to select the file. Looks like user has cancel it.")
        }
  
    });
    mediafilepicker.on("error", function (res) {
        console.log(res.msg)
    });
    mediafilepicker.startFilePicker(options);

**Comment by jibon57** [comment]
@sayeed360, did you get any error message?

**Comment by sayeed360** [comment]
My app exports a .db file and I'm trying to implement your plugin to restore that file. The problem is, when I generate a .db file with my app, your filepicker does not see the file. But if I put a .db file manually to the sd card, the file picker sees the file immediately. Checked with 2 devices, results are the same. Is there a  way to force rescan sd card with this plugin?

**Comment by jibon57** [comment]
@sayeed360 looks like this problem is related with Native Library of this plugin. Sorry, in this case I can't help you.

**Comment by sayeed360** [comment]
Ok, no problem, thank you for your time.
