### ISSUE TITLE
cannot select video files on iOS

### ISSUE THREAD

**Issue by bachras** [jibon57/nativescript-mediafilepicker#13]
Hi,

Thanks for great plugin. on Android it works as expected with both videos and images. iOs works fine with images, but once I select even one video file, press 'Done' and nothing gets returned. If I console results here is what I get: 
````
{"eventName":"getFiles","object":{"_observers":{"getFiles":[{}]},"output":""},"files":""}
````
If I select longer video, I click 'Done' and nothing happens.
Any help or advice is appreciated.

**Comment by jibon57** [comment]
@bachras Yes, big video file create problem because in iOS that file will copy to your app directory. So, if the file is too big then it will failed sometime. I don't have a perfect solution now. Here:

https://github.com/jibon57/nativescript-mediafilepicker/blob/e9eb1daa444448312811149043744fba4daeb08e/src/mediafilepicker.ios.ts#L144

I have written code to copy the file to app directory. So, you can try to avoid it & use `AVURLAsset` or `PHAsset` directly. In this case you may need to add your own customize code to handle further process because iOS won't allow you to use/make file's url like Android do. 

You can follow up here: https://github.com/jibon57/nativescript-mediafilepicker/issues/11
